/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedAdminRouteImport } from './routes/_authed.admin'
import { Route as AuthedProfileRouteImport } from './routes/_authed.profile'
import { Route as AuthedBoardsIndexRouteImport } from './routes/_authed.boards.index'
import { Route as AuthedBoardsBoardIdRouteImport } from './routes/_authed.boards.$boardId'
import { Route as AuthedBoardsArchivedRouteImport } from './routes/_authed.boards.archived'
import { Route as AuthedBoardsBoardIdIndexRouteImport } from './routes/_authed.boards.$boardId.index'
import { Route as AuthedBoardsBoardIdTasksTaskIdRouteImport } from './routes/_authed.boards.$boardId.tasks.$taskId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBoardsIndexRoute = AuthedBoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBoardsBoardIdRoute = AuthedBoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBoardsArchivedRoute = AuthedBoardsArchivedRouteImport.update({
  id: '/boards/archived',
  path: '/boards/archived',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBoardsBoardIdIndexRoute =
  AuthedBoardsBoardIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedBoardsBoardIdRoute,
  } as any)
const AuthedBoardsBoardIdTasksTaskIdRoute =
  AuthedBoardsBoardIdTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthedBoardsBoardIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthedAdminRoute
  '/profile': typeof AuthedProfileRoute
  '/boards/$boardId': typeof AuthedBoardsBoardIdRouteWithChildren
  '/boards/archived': typeof AuthedBoardsArchivedRoute
  '/boards/': typeof AuthedBoardsIndexRoute
  '/boards/$boardId/': typeof AuthedBoardsBoardIdIndexRoute
  '/boards/$boardId/tasks/$taskId': typeof AuthedBoardsBoardIdTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthedAdminRoute
  '/profile': typeof AuthedProfileRoute
  '/': typeof AuthedIndexRoute
  '/boards/archived': typeof AuthedBoardsArchivedRoute
  '/boards': typeof AuthedBoardsIndexRoute
  '/boards/$boardId': typeof AuthedBoardsBoardIdIndexRoute
  '/boards/$boardId/tasks/$taskId': typeof AuthedBoardsBoardIdTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/boards/$boardId': typeof AuthedBoardsBoardIdRouteWithChildren
  '/_authed/boards/archived': typeof AuthedBoardsArchivedRoute
  '/_authed/boards/': typeof AuthedBoardsIndexRoute
  '/_authed/boards/$boardId/': typeof AuthedBoardsBoardIdIndexRoute
  '/_authed/boards/$boardId/tasks/$taskId': typeof AuthedBoardsBoardIdTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/profile'
    | '/boards/$boardId'
    | '/boards/archived'
    | '/boards/'
    | '/boards/$boardId/'
    | '/boards/$boardId/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/profile'
    | '/'
    | '/boards/archived'
    | '/boards'
    | '/boards/$boardId'
    | '/boards/$boardId/tasks/$taskId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authed/admin'
    | '/_authed/profile'
    | '/_authed/'
    | '/_authed/boards/$boardId'
    | '/_authed/boards/archived'
    | '/_authed/boards/'
    | '/_authed/boards/$boardId/'
    | '/_authed/boards/$boardId/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/boards/': {
      id: '/_authed/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof AuthedBoardsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/boards/$boardId': {
      id: '/_authed/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof AuthedBoardsBoardIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/boards/archived': {
      id: '/_authed/boards/archived'
      path: '/boards/archived'
      fullPath: '/boards/archived'
      preLoaderRoute: typeof AuthedBoardsArchivedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/boards/$boardId/': {
      id: '/_authed/boards/$boardId/'
      path: '/'
      fullPath: '/boards/$boardId/'
      preLoaderRoute: typeof AuthedBoardsBoardIdIndexRouteImport
      parentRoute: typeof AuthedBoardsBoardIdRoute
    }
    '/_authed/boards/$boardId/tasks/$taskId': {
      id: '/_authed/boards/$boardId/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/boards/$boardId/tasks/$taskId'
      preLoaderRoute: typeof AuthedBoardsBoardIdTasksTaskIdRouteImport
      parentRoute: typeof AuthedBoardsBoardIdRoute
    }
  }
}

interface AuthedBoardsBoardIdRouteChildren {
  AuthedBoardsBoardIdIndexRoute: typeof AuthedBoardsBoardIdIndexRoute
  AuthedBoardsBoardIdTasksTaskIdRoute: typeof AuthedBoardsBoardIdTasksTaskIdRoute
}

const AuthedBoardsBoardIdRouteChildren: AuthedBoardsBoardIdRouteChildren = {
  AuthedBoardsBoardIdIndexRoute: AuthedBoardsBoardIdIndexRoute,
  AuthedBoardsBoardIdTasksTaskIdRoute: AuthedBoardsBoardIdTasksTaskIdRoute,
}

const AuthedBoardsBoardIdRouteWithChildren =
  AuthedBoardsBoardIdRoute._addFileChildren(AuthedBoardsBoardIdRouteChildren)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedBoardsBoardIdRoute: typeof AuthedBoardsBoardIdRouteWithChildren
  AuthedBoardsArchivedRoute: typeof AuthedBoardsArchivedRoute
  AuthedBoardsIndexRoute: typeof AuthedBoardsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedBoardsBoardIdRoute: AuthedBoardsBoardIdRouteWithChildren,
  AuthedBoardsArchivedRoute: AuthedBoardsArchivedRoute,
  AuthedBoardsIndexRoute: AuthedBoardsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
